log-format TRAEFIKCLF
config-dialog false
hl-header true
json-pretty-print false
no-color false
no-column-names false
no-csv-summary false
no-progress false
no-tab-scroll false
tz UTC
with-mouse false
addr 127.0.0.1
daemonize false
port 7890
real-time-html true
ws-url {{WS}}
agent-list true
with-output-resolver true
http-method yes
http-protocol yes
no-query-string false
no-term-resolver false
444-as-404 false
4xx-to-unique-count false
anonymize-ip false
all-static-files false
browsers-file {{BROWSERS}}
date-spec hr
double-decode false
hour-spec min
ignore-crawlers false
crawlers-only false
unknowns-as-crawlers false
num-tests 0
real-os true
persist true
restore false
keep-last {{DAYS}}
