apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accessrelay.fullname" . }}-config
  labels:
    {{- include "accessrelay.labels" . | nindent 4 }}
data:
  accessrelay.json: {{ .Values.config | toJson | quote }}
