{{- if not .Values.storage.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "accessrelay.fullname" . }}-state
  labels:
    {{- include "accessrelay.labels" . | nindent 4 }}
    {{- with .Values.storage.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.storage.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes: [ReadWriteOnce]
  {{- with .Values.storage.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}
