apiVersion: v1
kind: Service
metadata:
  name: {{ include "accessrelay.fullname" . }}
  labels:
    {{- include "accessrelay.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "accessrelay.selector" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
---
{{- if .Values.authService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.authService.name }}
spec:
  type: ExternalName
  externalName: {{ required "authService.externalName is required" .Values.authService.externalName }}
  ports:
    - name: http
      port: {{ .Values.authService.port }}
{{- end }}
